hostData = [
  {
    "name": "Porom",
    "username": "porom",
    "password": "test",
    "dateOfBirth": "2002-02-02",
    "SIN": 123456789,
    "address": "123 Main Street",
    "occupation": "Student",
  },
  {
    "name": "Luneth",
    "username": "luneth",
    "password": "pass123",
    "dateOfBirth": "1998-07-15",
    "SIN": 987654321,
    "address": "456 Elm Avenue",
    "occupation": "Student",
  },
  {
    "name": "Terra",
    "username": "terra",
    "password": "terra456",
    "dateOfBirth": "1985-04-10",
    "SIN": 456789123,
    "address": "789 Oak Road",
    "occupation": "Student",
  },
  {
    "name": "Cecil",
    "username": "cecil",
    "password": "knight22",
    "dateOfBirth": "1990-12-20",
    "SIN": 789123456,
    "address": "567 Pine Lane",
    "occupation": "Student",
  },
  {
    "name": "Aerith",
    "username": "aerith",
    "password": "flower1",
    "dateOfBirth": "1987-02-07",
    "SIN": 159753852,
    "address": "234 Rose Street",
    "occupation": "Student",
  },
  {
    "name": "Locke",
    "username": "locke",
    "password": "treasure12",
    "dateOfBirth": "1993-09-25",
    "SIN": 852963741,
    "address": "789 Key Avenue",
    "occupation": "Student",
  },
  {
    "name": "Rinoa",
    "username": "rinoa",
    "password": "squall456",
    "dateOfBirth": "1998-03-03",
    "SIN": 369852147,
    "address": "123 Angel Boulevard",
    "occupation": "Student",
  },
  {
    "name": "Cloud",
    "username": "cloud",
    "password": "bustersword",
    "dateOfBirth": "1986-08-11",
    "SIN": 456123789,
    "address": "456 Mako Street",
    "occupation": "Student",
  },
  {
    "name": "Eiko",
    "username": "eiko",
    "password": "summons123",
    "dateOfBirth": "2000-11-30",
    "SIN": 987654123,
    "address": "789 Summoner Lane",
    "occupation": "Student",
  },
  {
    "name": "Sabin",
    "username": "sabin",
    "password": "suplex22",
    "dateOfBirth": "1984-06-18",
    "SIN": 321987654,
    "address": "567 Blitz Avenue",
    "occupation": "Student",
  },
]

rentersData = [
  {
    "name": "Eleanor",
    "username": "eleanor_smith",
    "password": "securepass123",
    "dateOfBirth": "1990-09-20",
    "SIN": 654321987,
    "address": "456 Elm Street, Anytown, USA",
    "occupation": "Accountant",
  },
  {
    "name": "David",
    "username": "david_jones",
    "password": "strongpw456",
    "dateOfBirth": "1985-03-12",
    "SIN": 789012345,
    "address": "789 Maple Avenue, Cityville, USA",
    "occupation": "Software Engineer",
  },
  {
    "name": "Sophia",
    "username": "sophia_wilson",
    "password": "safepassword789",
    "dateOfBirth": "1995-07-03",
    "SIN": 123450987,
    "address": "123 Oak Street, Townsville, USA",
    "occupation": "Teacher",
  },
  {
    "name": "Marcus",
    "username": "marcus_davis",
    "password": "123456pass",
    "dateOfBirth": "1982-11-15",
    "SIN": 567870123,
    "address": "567 Pine Road, Villagetown, USA",
    "occupation": "Lawyer",
  },
  {
    "name": "Isabella",
    "username": "isabella_wright",
    "password": "securepw987",
    "dateOfBirth": "1978-12-30",
    "SIN": 901234567,
    "address": "234 Cedar Street, Hamletville, USA",
    "occupation": "Doctor",
  },
  {
    "name": "Daniel",
    "username": "daniel_brown",
    "password": "password123",
    "dateOfBirth": "1998-05-02",
    "SIN": 345678901,
    "address": "789 Willow Avenue, Riverside, USA",
    "occupation": "Marketing Manager",
  },
  {
    "name": "Olivia",
    "username": "olivia_smith",
    "password": "strong123",
    "dateOfBirth": "1993-08-18",
    "SIN": 678901234,
    "address": "456 Birch Road, Lakeside, USA",
    "occupation": "Graphic Designer",
  },
  {
    "name": "Liam",
    "username": "liam_jackson",
    "password": "pass456",
    "dateOfBirth": "1989-01-25",
    "SIN": 890123456,
    "address": "123 Rose Avenue, Mountainview, USA",
    "occupation": "Financial Analyst",
  },
  {
    "name": "Emma",
    "username": "emma_wilson",
    "password": "secure789",
    "dateOfBirth": "1997-06-10",
    "SIN": 123456012,
    "address": "789 Willow Street, Seaside, USA",
    "occupation": "Writer",
  },
  {
    "name": "Noah",
    "username": "noah_thomas",
    "password": "123pass",
    "dateOfBirth": "1984-04-08",
    "SIN": 345778901,
    "address": "567 Lake Road, Sunrise, USA",
    "occupation": "Architect",
  },
  {
    "name": "Ava",
    "username": "ava_anderson",
    "password": "456secure",
    "dateOfBirth": "1991-02-14",
    "SIN": 567890123,
    "address": "234 Meadow Avenue, Sunset, USA",
    "occupation": "Photographer",
  },
]

listingData = [
  {
    "address": "123 Main St",
    "city": "Anytown",
    "country": "USA",
    "postalCode": "H9H0H0",
    "longitude": 33.045,
    "latitude": -71.012,
    "price": 200
  },
  {
    "address": "456 Elm Ave",
    "city": "Cityville",
    "country": "USA",
    "postalCode": "H9H1H1",
    "longitude": 33.075,
    "latitude": -70.985,
    "price": 350
  },
  {
    "address": "789 Maple Rd",
    "city": "Townsville",
    "country": "USA",
    "postalCode": "H9H2H2",
    "longitude": 32.963,
    "latitude": -71.108,
    "price": 280
  },
  {
    "address": "234 Cedar St",
    "city": "Hamletville",
    "country": "USA",
    "postalCode": "H9H3H3",
    "longitude": 32.978,
    "latitude": -71.054,
    "price": 42
  },
  {
    "address": "567 Pine Rd",
    "city": "Villagetown",
    "country": "USA",
    "postalCode": "H9H4H4",
    "longitude": 33.033,
    "latitude": -71.101,
    "price": 50
  },
  {
    "address": "789 Willow Ave",
    "city": "Riverside",
    "country": "USA",
    "postalCode": "H9H5H5",
    "longitude": 32.992,
    "latitude": -71.040,
    "price": 320
  },
  {
    "address": "123 Rose St",
    "city": "Mountainview",
    "country": "USA",
    "postalCode": "H9H6H6",
    "longitude": 33.019,
    "latitude": -71.085,
    "price": 370
  },
  {
    "address": "456 Birch Rd",
    "city": "Lakeside",
    "country": "USA",
    "postalCode": "H9H7H7",
    "longitude": 33.060,
    "latitude": -70.990,
    "price": 29
  },
  {
    "address": "789 Willow St",
    "city": "Seaside",
    "country": "USA",
    "postalCode": "H9H8H8",
    "longitude": 33.000,
    "latitude": -71.131,
    "price": 410
  },
  {
    "address": "567 Lake Rd",
    "city": "Sunrise",
    "country": "USA",
    "postalCode": "H9H9H9",
    "longitude": 32.951,
    "latitude": -71.063,
    "price": 380
  },
  {
    "address": "789 Park Lane",
    "city": "Greenville",
    "country": "USA",
    "postalCode": "A1A1A1",
    "longitude": 33.012345,
    "latitude": -70.968765,
    "price": 725
  },
  {
    "address": "123 Forest Ave",
    "city": "Greenville",
    "country": "USA",
    "postalCode": "A2A2A2",
    "longitude": 33.009876,
    "latitude": -71.031234,
    "price": 825
  },
  {
    "address": "456 Ocean Rd",
    "city": "Greenville",
    "country": "USA",
    "postalCode": "A3A3A3",
    "longitude": 33.080123,
    "latitude": -71.027589,
    "price": 550
  },
  {
    "address": "789 Mountain View Dr",
    "city": "Greenville",
    "country": "USA",
    "postalCode": "A4A4A4",
    "longitude": 33.050678,
    "latitude": -70.981234,
    "price": 620
  },
  {
    "address": "123 River Ave",
    "city": "Rivertown",
    "country": "Canada",
    "postalCode": "A5A5A5",
    "longitude": 33.020123,
    "latitude": -70.993456,
    "price": 510
  },
  {
    "address": "456 Meadow Ln",
    "city": "Meadowville",
    "country": "United Kingdom",
    "postalCode": "A6A6A6",
    "longitude": 32.998765,
    "latitude": -71.017890,
    "price": 690
  },
  {
    "address": "789 Sunset Blvd",
    "city": "Sunset City",
    "country": "Australia",
    "postalCode": "A7A7A7",
    "longitude": 33.031234,
    "latitude": -71.073456,
    "price": 710
  },
  {
    "address": "123 Lakeview Rd",
    "city": "Lakeview",
    "country": "Germany",
    "postalCode": "A8A8A8",
    "longitude": 33.065432,
    "latitude": -70.955678,
    "price": 580
  },
  {
    "address": "456 Hilltop Ave",
    "city": "Hilltop",
    "country": "France",
    "postalCode": "A9A9A9",
    "longitude": 33.044321,
    "latitude": -70.999012,
    "price": 670
  },
  {
    "address": "789 Valley Rd",
    "city": "Valleyville",
    "country": "Spain",
    "postalCode": "B0B0B0",
    "longitude": 33.027589,
    "latitude": -70.945678,
    "price": 720
  },
  {
    "address": "123 Ocean View",
    "city": "Beachtown",
    "country": "Australia",
    "postalCode": "B1B1B1",
    "longitude": 33.015678,
    "latitude": -71.082345,
    "price": 590
  },
  {
    "address": "456 Mountain Rd",
    "city": "Mountainville",
    "country": "Canada",
    "postalCode": "B2B2B2",
    "longitude": 33.035432,
    "latitude": -70.974567,
    "price": 670
  },
  {
    "address": "789 Lakeside Ave",
    "city": "Lakeview",
    "country": "USA",
    "postalCode": "B3B3B3",
    "longitude": 33.045678,
    "latitude": -71.012345,
    "price": 550
  },
  {
    "address": "123 Hilltop Dr",
    "city": "Hilltop",
    "country": "United Kingdom",
    "postalCode": "B4B4B4",
    "longitude": 32.999012,
    "latitude": -70.991234,
    "price": 750
  },
  {
    "address": "456 Valley View",
    "city": "Valleyville",
    "country": "France",
    "postalCode": "B5B5B5",
    "longitude": 33.025678,
    "latitude": -70.961234,
    "price": 620
  },
  {
    "address": "789 Riverside Rd",
    "city": "Rivertown",
    "country": "Spain",
    "postalCode": "B6B6B6",
    "longitude": 33.019012,
    "latitude": -70.998765,
    "price": 680
  },
  {
    "address": "123 Meadow Ln",
    "city": "Meadowville",
    "country": "Germany",
    "postalCode": "B7B7B7",
    "longitude": 33.055432,
    "latitude": -71.020123,
    "price": 710
  },
  {
    "address": "456 Sunset Blvd",
    "city": "Sunset City",
    "country": "Italy",
    "postalCode": "B8B8B8",
    "longitude": 33.030123,
    "latitude": -71.065432,
    "price": 570
  },
  {
    "address": "789 Forest Ave",
    "city": "Woodville",
    "country": "Canada",
    "postalCode": "B9B9B9",
    "longitude": 33.000123,
    "latitude": -70.980123,
    "price": 720
  },
  {
    "address": "123 Ocean Rd",
    "city": "Beachtown",
    "country": "Australia",
    "postalCode": "C0C0C0",
    "longitude": 33.081234,
    "latitude": -70.952345,
    "price": 650
  }
]

ratingData = [
    {"rating": 3, "comment": "Average stay, nothing special."},
    {"rating": 4, "comment": "Decent place, could use some improvements."},
    {"rating": 2, "comment": "Not a good experience at all."},
    {"rating": 5, "comment": "Nice stay, great amenities."},
    {"rating": 1, "comment": "Terrible service and conditions."},
    {"rating": 3, "comment": "Satisfactory stay, would consider staying again."},
    {"rating": 4, "comment": "Good experience overall."},
    {"rating": 2, "comment": "Disappointing, didn't meet expectations."},
    {"rating": 5, "comment": "Excellent stay, highly recommended."},
    {"rating": 1, "comment": "Worst experience ever."},
    {"rating": 4, "comment": "Almost perfect, just a few minor issues."},
    {"rating": 3, "comment": "Could have been better, but not bad."},
    {"rating": 2, "comment": "Unpleasant stay, wouldn't recommend."},
    {"rating": 5, "comment": "Absolutely loved it, will definitely come back."},
    {"rating": 3, "comment": "Adequate stay, met basic requirements."},
    {"rating": 1, "comment": "Horrible service and conditions."},
    {"rating": 4, "comment": "Enjoyable experience, nice amenities."},
    {"rating": 2, "comment": "Awful stay, wouldn't return."},
    {"rating": 5, "comment": "Outstanding, exceeded expectations."},
    {"rating": 3, "comment": "Decent value for the price."},
    {"rating": 4, "comment": "Pleasant stay, would recommend."},
    {"rating": 2, "comment": "Not worth the money."},
    {"rating": 1, "comment": "Regret staying here."},
    {"rating": 5, "comment": "Fantastic, one of the best stays."},
    {"rating": 3, "comment": "Average stay, nothing extraordinary."},
    {"rating": 4, "comment": "Good value for the price."},
    {"rating": 2, "comment": "Poor experience, wouldn't come back."},
    {"rating": 1, "comment": "Absolutely awful, avoid at all costs."},
    {"rating": 5, "comment": "Exemplary, exceeded all expectations."},
    {"rating": 3, "comment": "Satisfactory stay, met expectations."},
]

renterRatingData = [
  {"rating": 3, "comment": "Average renter, nothing special."},
  {"rating": 4, "comment": "Decent renter, could use some improvements."},
  {"rating": 2, "comment": "Not a good experience at all."},
  {"rating": 5, "comment": "Nice renter, great communication."},
  {"rating": 1, "comment": "Terrible service and conditions."},
  {"rating": 3, "comment": "Satisfactory renter, would consider renting again."},
  {"rating": 4, "comment": "Good experience overall."},
  {"rating": 2, "comment": "Disappointing, didn't meet expectations."},
  {"rating": 5, "comment": "Excellent renter, highly recommended."},
  {"rating": 1, "comment": "Worst experience ever."},
  {"rating": 4, "comment": "Almost perfect, just a few minor issues."},
  {"rating": 3, "comment": "Could have been better, but not bad."},
  {"rating": 2, "comment": "Unpleasant renter, wouldn't recommend."},
  {"rating": 5, "comment": "Absolutely loved it, will definitely rent again."},
  {"rating": 3, "comment": "Adequate renter, met basic requirements."},
  {"rating": 1, "comment": "Horrible service and conditions."}
]